### PR TITLE
basic: Added a reprocess command

### PR DESCRIPTION
**Pull request by mrshu**
* Added a reprocess command which kind of 'repeats' the last command or
  a message of a user to a given bot.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
to @pepol @Adman 

I couldn't find a better name than this. `reprocess` seems artificial (and lacks the "what" part), `repeat` has the same problem so `r` it is.

**Comment by pepol** [comment]
@mrshu what about `redo`?

**Comment by mrshu** [comment]
@pepol yeah, that might work. However, I'd still like to keep the the short `r`.

**Comment by pepol** [comment]
Sure, it was just an idea (or maybe even `.` as in vim command repeat could work? :-D) otherwise LGTM!

**Comment by mrshu** [comment]
@pepol that would imply you are in normal mode =)

**Comment by pepol** [comment]
Well one more thing though. Do we really want to use `'''` for docstrings? I mean there are some (older) functions using `"""` in this file and the new ones using `'''`. Also, IIRC, it is preferred to use `"""` for docstrings (but this may be Google-specific, not PEP8, I'm not sure here).

**Comment by mrshu** [comment]
@pepol good catch!

That was some sort of a misunderstanding between my two selves in different points in time.

What I plan to do with this is to leave it as it is and create an "easy" bug for someone who wants to get acquainted with the codebase to consolidate these docstring brackets in this file.

**Pull request merged**
