### PR TITLE
url_matcher: Fixed issues with file size check

### PR DESCRIPTION
**Pull request by mrshu**
* Sometimes there is (obviously) no 'content-length'. This commit tries
  to prevent those situations when it could be missing.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
to @pepol @Adman

**Comment by pepol** [comment]
lgtm

**Comment by pepol** [comment]
However, what if this response (without content-length) is too big? Let's say 100 GB?

**Comment by mrshu** [comment]
@pepol then the problem is on another level =)

In my tests this only concerns `https://` URLs. In that case there is not really too much we can do about it.

**Comment by pepol** [comment]
@mrshu maybe a stupid question but why is `Content-length` problem in HTTPS?

**Comment by belslag** [comment]
DuckDuckGo in the Chrome Webstore

**Comment by belslag** [comment]
Nice

**Comment by Adman** [comment]
LGTM

**Comment by mrshu** [comment]
@pepol very good question.

I have no idea, really. Anyhow, if we do not know the size from what there is in headers that's about everything we can do.

**Pull request merged**
