### PR TITLE
requirements: Pin cpsk's new version

### PR DESCRIPTION
**Pull request by mrshu**
* Pin new version of cpsk module that adds delays of trains.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
to @Adman 
cc @pepol

**Comment by Adman** [comment]
@mrshu I'm working on 0.1.1, where it is possible to show platform. So we probably want to add that one.

**Comment by Adman** [comment]
@mrshu Feel free to add 0.1.1 there, it's done.

**Comment by mrshu** [comment]
@Adman should be there now.

**Pull request merged**
