### PR TITLE
sticky-notes: Flood fix & typo fix

### PR DESCRIPTION
**Pull request by mrshu**
* Fixed the issue of not being able to send all messages at once
  (occured due to excessive message flood restrictions).

* Fixed small issue with iteration over notes: we never caught the last
  note.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
to @pepol 

cc @Adman, (LordPotato??)

**Comment by pepol** [comment]
LGTM

**Comment by Adman** [comment]
LGTM

**Comment by mrshu** [comment]
cc @tWido

**Comment by mrshu** [comment]
Thanks @pepol, @Adman, I'm merging this.

**Pull request merged**
